name: build

on: [push, pull_request]

jobs:
    windows:
        runs-on: windows-latest
        steps:
        - uses: actions/checkout@v1
        - name: win64-vstudio-debug
          run:  python3 fips build win64-vstudio-debug
        - name: win64-vstudio-release
          run:  python3 fips build win64-vstudio-release
        - name: Upload Windows package to release
          uses: svenstaro/upload-release-action@v2
          if: startsWith(github.ref, 'refs/tags/v')
          with:
            repo_token: ${{ secrets.GHACTION_PUSH }}
            file: ../fips-deploy/yame/win64-vstudio-release/*
            tag: ${{ github.ref }}
            overwrite: true
            file_glob: true
    mac:
        runs-on: macos-latest
        steps:
        - uses: actions/checkout@v1
        - name: osx-make-debug
          run:  python3 fips build osx-make-debug
        - name: osx-make-release
          run:  python3 fips build osx-make-release
        - name: Upload mo5 macOS package to release
          uses: svenstaro/upload-release-action@v2
          if: startsWith(github.ref, 'refs/tags/v')
          with:
            repo_token: ${{ secrets.GHACTION_PUSH }}
            file: ../fips-deploy/yame/osx-make-release/mo5
            asset_name: mo5-mac
            tag: ${{ github.ref }}
            overwrite: true
            file_glob: false
        - name: Upload mo5-ui macOS package to release
          uses: svenstaro/upload-release-action@v2
          if: startsWith(github.ref, 'refs/tags/v')
          with:
            repo_token: ${{ secrets.GHACTION_PUSH }}
            file: ../fips-deploy/yame/osx-make-release/mo5-ui
            asset_name: mo5-ui-mac
            tag: ${{ github.ref }}
            overwrite: true
            file_glob: false
    linux:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
        - name: prepare
          run:  |
            sudo apt-get update
            sudo apt-get install libglu1-mesa-dev mesa-common-dev xorg-dev libasound-dev
        - name: linux-make-debug
          run:  python3 fips build linux-make-debug
        - name: linux-make-release
          run:  python3 fips build linux-make-release
        - name: Upload mo5 Ubuntu package to release
          uses: svenstaro/upload-release-action@v2
          if: startsWith(github.ref, 'refs/tags/v')
          with:
            repo_token: ${{ secrets.GHACTION_PUSH }}
            file: ../fips-deploy/yame/linux-make-release/mo5
            asset_name: mo5-linux
            tag: ${{ github.ref }}
            overwrite: true
            file_glob: false
        - name: Upload mo5-ui Ubuntu package to release
          uses: svenstaro/upload-release-action@v2
          if: startsWith(github.ref, 'refs/tags/v')
          with:
            repo_token: ${{ secrets.GHACTION_PUSH }}
            file: ../fips-deploy/yame/linux-make-release/mo5-ui
            asset_name: mo5-ui-linux
            tag: ${{ github.ref }}
            overwrite: true
            file_glob: false
    emscripten:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
        - name: install emsdk
          run: |
            sudo apt-get install ninja-build
            python3 fips emsdk install latest
        - name: wasm-ninja-debug
          run:  python3 fips build wasm-ninja-debug
        - name: wasm-ninja-release
          run:  python3 fips build wasm-ninja-release
