name: Deploy Webpage
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: seanmiddleditch/gha-setup-ninja@master
      - name: prepare
        run: |
          sudo apt update
          sudo apt install webp
          python3 fips emsdk install latest
      - name: build
        run: |
          python3 fips set local on
          python3 fips webpage build
      - name: upload-artifact
        uses: actions/upload-artifact@main
        with:
          name: webpage
          path: fips-files/deploy/yame-webpage
          retention-days: 1
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          repository: scemino/yame_wp
          ssh-key: ${{ secrets.GHACTION_PUSH }}
      - uses: actions/download-artifact@main
        with:
          name: webpage
      - name: "commit and push"
        run: |
          git config user.email "none"
          git config user.name "GH Action"
          git add .
          git commit -m "updated (${{ github.run_number }})"
          git push
